import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Progress } from "@/components/ui/progress";
import { ArrowLeft, Play, CheckCircle, XCircle, MessageSquare } from "lucide-react";
import { demoMeetings, Task } from "@/data/meetings";
import { useToast } from "@/hooks/use-toast";

interface TaskResponse {
  taskId: string;
  completed: boolean;
  reason: string;
}

const ConversationPage = () => {
  const { meetingId } = useParams();
  const navigate = useNavigate();
  const { toast } = useToast();
  
  const [meeting, setMeeting] = useState(demoMeetings.find(m => m.id === meetingId));
  const [meetingStarted, setMeetingStarted] = useState(false);
  const [currentTaskIndex, setCurrentTaskIndex] = useState(0);
  const [taskResponses, setTaskResponses] = useState<TaskResponse[]>([]);
  const [currentAnswer, setCurrentAnswer] = useState<boolean | null>(null);
  const [currentReason, setCurrentReason] = useState("");
  const [showSummary, setShowSummary] = useState(false);
  const [aiSummary, setAiSummary] = useState("");

  useEffect(() => {
    if (!meeting) {
      navigate('/');
      return;
    }
  }, [meeting, navigate]);

  const handleStartMeeting = () => {
    setMeetingStarted(true);
    toast({
      title: "Meeting Started",
      description: "Beginning task review process...",
    });
  };

  const handleTaskAnswer = (completed: boolean) => {
    setCurrentAnswer(completed);
  };

  const handleSubmitTaskResponse = () => {
    if (currentAnswer === null || !currentReason.trim()) {
      toast({
        title: "Incomplete Response",
        description: "Please answer the question and provide details.",
        variant: "destructive",
      });
      return;
    }

    const response: TaskResponse = {
      taskId: meeting!.tasks[currentTaskIndex].id,
      completed: currentAnswer,
      reason: currentReason,
    };

    setTaskResponses([...taskResponses, response]);
    setCurrentAnswer(null);
    setCurrentReason("");

    if (currentTaskIndex < meeting!.tasks.length - 1) {
      setCurrentTaskIndex(currentTaskIndex + 1);
    } else {
      generateAISummary([...taskResponses, response]);
    }
  };

  const generateAISummary = (responses: TaskResponse[]) => {
    // Simulate AI processing
    toast({
      title: "Generating Summary",
      description: "AI is analyzing responses...",
    });

    setTimeout(() => {
      const completedTasks = responses.filter(r => r.completed).length;
      const totalTasks = responses.length;
      
      const summary = `# Meeting Summary - ${meeting!.title}

## Agenda
${meeting!.agenda}

## Task Progress Review
**Completed:** ${completedTasks}/${totalTasks} tasks

### Task Status:
${responses.map((response, index) => {
  const task = meeting!.tasks[index];
  return `**${task.title}** (${task.assignee})
- Status: ${response.completed ? '✅ Completed' : '❌ Not Completed'}
- Details: ${response.reason}`;
}).join('\n\n')}

## Key Insights
- Team completion rate: ${Math.round((completedTasks / totalTasks) * 100)}%
${responses.filter(r => !r.completed).length > 0 ? 
  `- ${responses.filter(r => !r.completed).length} task(s) require follow-up` : 
  '- All planned tasks were successfully completed'}

## Next Action Items
- Review and address any blocked or incomplete tasks
- Plan next sprint based on current progress
- Schedule follow-up sessions for complex challenges

## Decisions Made
${meeting!.decisions}

## Identified Blockers
${meeting!.blockers}

*Summary generated by iCog Sync AI on ${new Date().toLocaleDateString()}*`;

      setAiSummary(summary);
      setShowSummary(true);
      
      toast({
        title: "Summary Generated",
        description: "Meeting analysis complete!",
      });
    }, 2000);
  };

  if (!meeting) return null;

  const currentTask = meeting.tasks[currentTaskIndex];
  const progress = meetingStarted ? ((currentTaskIndex + (currentAnswer !== null ? 0.5 : 0)) / meeting.tasks.length) * 100 : 0;

  return (
    <div className="min-h-screen bg-gradient-subtle">
      {/* Header */}
      <div className="bg-card border-b shadow-soft">
        <div className="container mx-auto px-6 py-6">
          <div className="flex items-center gap-4">
            <Button 
              variant="secondary" 
              size="sm"
              onClick={() => navigate('/')}
              className="hover:bg-secondary-hover"
            >
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Meetings
            </Button>
            <div>
              <h1 className="text-2xl font-bold text-card-foreground">
                {meeting.title}
              </h1>
              <p className="text-muted-foreground">
                {new Date(meeting.date).toLocaleDateString()} at {meeting.time}
              </p>
            </div>
          </div>
          
          {meetingStarted && (
            <div className="mt-4">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm text-muted-foreground">Progress</span>
                <span className="text-sm font-medium">{Math.round(progress)}%</span>
              </div>
              <Progress value={progress} className="h-2" />
            </div>
          )}
        </div>
      </div>

      <div className="container mx-auto px-6 py-8">
        {!meetingStarted ? (
          /* Meeting Overview */
          <div className="max-w-4xl mx-auto space-y-6">
            <Card className="bg-card/80 backdrop-blur-sm border-border/50">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <MessageSquare className="h-5 w-5 text-primary" />
                  Meeting Details
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid md:grid-cols-2 gap-6">
                  <div>
                    <h3 className="font-semibold mb-2">Agenda</h3>
                    <p className="text-muted-foreground">{meeting.agenda}</p>
                  </div>
                  <div>
                    <h3 className="font-semibold mb-2">Updates</h3>
                    <p className="text-muted-foreground">{meeting.updates}</p>
                  </div>
                  <div>
                    <h3 className="font-semibold mb-2">Decisions</h3>
                    <p className="text-muted-foreground">{meeting.decisions}</p>
                  </div>
                  <div>
                    <h3 className="font-semibold mb-2">Blockers</h3>
                    <p className="text-muted-foreground">{meeting.blockers}</p>
                  </div>
                </div>
              </CardContent>
            </Card>

            <Card className="bg-card/80 backdrop-blur-sm border-border/50">
              <CardHeader>
                <CardTitle>Tasks to Review</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {meeting.tasks.map((task, index) => (
                    <div key={task.id} className="flex items-center justify-between p-3 border border-border/50 rounded-md">
                      <div>
                        <p className="font-medium">{task.title}</p>
                        <p className="text-sm text-muted-foreground">
                          Assigned to {task.assignee} • Due {new Date(task.deadline).toLocaleDateString()}
                        </p>
                      </div>
                      <Badge variant="secondary">{index + 1}</Badge>
                    </div>
                  ))}
                </div>
                
                <div className="mt-6 text-center">
                  <Button 
                    onClick={handleStartMeeting} 
                    size="lg"
                    className="bg-primary hover:bg-primary-hover text-primary-foreground px-8"
                  >
                    <Play className="h-4 w-4 mr-2" />
                    Start Meeting
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        ) : showSummary ? (
          /* AI Summary */
          <div className="max-w-4xl mx-auto">
            <Card className="bg-card/80 backdrop-blur-sm border-border/50">
              <CardHeader>
                <CardTitle className="text-center text-primary">
                  Meeting Summary Generated
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="prose max-w-none">
                  <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed text-card-foreground">
                    {aiSummary}
                  </pre>
                </div>
                
                <div className="mt-6 flex justify-center gap-4">
                  <Button 
                    variant="secondary"
                    onClick={() => navigate('/')}
                  >
                    Back to Meetings
                  </Button>
                  <Button 
                    onClick={() => {
                      navigator.clipboard.writeText(aiSummary);
                      toast({
                        title: "Copied!",
                        description: "Summary copied to clipboard",
                      });
                    }}
                  >
                    Copy Summary
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        ) : (
          /* Task Q&A Flow */
          <div className="max-w-2xl mx-auto">
            <Card className="bg-card/80 backdrop-blur-sm border-border/50">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle>Task Review</CardTitle>
                  <Badge variant="outline">
                    {currentTaskIndex + 1} of {meeting.tasks.length}
                  </Badge>
                </div>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="text-center p-6 bg-secondary/50 rounded-lg">
                  <h3 className="text-xl font-semibold mb-2">{currentTask.title}</h3>
                  <p className="text-muted-foreground">
                    Assigned to {currentTask.assignee} • Due {new Date(currentTask.deadline).toLocaleDateString()}
                  </p>
                </div>

                <div className="text-center">
                  <h4 className="text-lg font-medium mb-4">Was this task completed?</h4>
                  
                  <div className="flex justify-center gap-4 mb-6">
                    <Button
                      variant={currentAnswer === true ? "default" : "outline"}
                      onClick={() => handleTaskAnswer(true)}
                      className="flex items-center gap-2"
                    >
                      <CheckCircle className="h-4 w-4" />
                      Yes, Completed
                    </Button>
                    <Button
                      variant={currentAnswer === false ? "default" : "outline"}
                      onClick={() => handleTaskAnswer(false)}
                      className="flex items-center gap-2"
                    >
                      <XCircle className="h-4 w-4" />
                      No, Not Completed
                    </Button>
                  </div>
                </div>

                {currentAnswer !== null && (
                  <div className="space-y-4">
                    <Separator />
                    <div>
                      <label className="text-sm font-medium">
                        {currentAnswer ? "Did you face any challenges?" : "Why was it not completed?"}
                      </label>
                      <textarea
                        value={currentReason}
                        onChange={(e) => setCurrentReason(e.target.value)}
                        className="w-full mt-2 p-3 border border-border rounded-md bg-background text-foreground focus:ring-2 focus:ring-primary focus:border-transparent"
                        rows={3}
                        placeholder="Provide details..."
                      />
                    </div>
                    
                    <Button 
                      onClick={handleSubmitTaskResponse}
                      disabled={!currentReason.trim()}
                      className="w-full"
                    >
                      {currentTaskIndex < meeting.tasks.length - 1 ? "Next Task" : "Generate Summary"}
                    </Button>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        )}
      </div>
    </div>
  );
};

export default ConversationPage;